# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('maqr', ['internet', 'wifi'])
    module.source = [
        'model/maqr-neighbor.cc',
        'model/maqr-packet.cc',
        'model/maqr-rl-learning.cc',
        'model/maqr-routing-protocol.cc',
        'model/maqr-rqueue.cc',
        'model/maqr-rtable.cc',
        'helper/maqr-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('maqr')
    module_test.source = [
        'test/maqr-test-suite.cc',
        ]
    # Tests encapsulating example programs should be listed here
    if (bld.env['ENABLE_EXAMPLES']):
        module_test.source.extend([
        #    'test/maqr-examples-test-suite.cc',
             ])

    headers = bld(features='ns3header')
    headers.module = 'maqr'
    headers.source = [
        'model/maqr-neighbor.h',
        'model/maqr-packet.h',
        'model/maqr-rl-learning.h',
        'model/maqr-routing-protocol.h',
        'model/maqr-rqueue.h',
        'model/maqr-rtable.h',
        'helper/maqr-helper.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

