# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('saqr', ['internet', 'wifi'])
    module.source = [
        'model/saqr-neighbor.cc',
        'model/saqr-packet.cc',
        'model/saqr-rl-learning.cc',
        'model/saqr-routing-protocol.cc',
        'model/saqr-rqueue.cc',
        'model/saqr-rtable.cc',
        'helper/saqr-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('saqr')
    module_test.source = [
        'test/saqr-test-suite.cc',
        ]
    # Tests encapsulating example programs should be listed here
    if (bld.env['ENABLE_EXAMPLES']):
        module_test.source.extend([
        #    'test/saqr-examples-test-suite.cc',
             ])

    headers = bld(features='ns3header')
    headers.module = 'saqr'
    headers.source = [
        'model/saqr-neighbor.h',
        'model/saqr-packet.h',
        'model/saqr-rl-learning.h',
        'model/saqr-routing-protocol.h',
        'model/saqr-rqueue.h',
        'model/saqr-rtable.h',
        'helper/saqr-helper.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

